### ISSUE TITLE
demo_minimal_c not working

### ISSUE THREAD

**Issue by rviertel2** [hcebke/libQEx#5]
I was able to get OpenMesh and libQex to build just fine, but when I try to run demo_minimal_c the only output I get is

Got the following output quad mesh:

I modified the source file to print quadMesh.quad_count and I get

quadMesh.quad_count = 0

**Comment by hcebke** [comment]
I committed what I believe should be a fix for your problem. (I'm actually surprised this issue didn't blow up into my face much sooner.) Could you confirm this fix?

**Comment by ghost** [comment]
I pulled the change and recompiled and now I get

Got the following output quad mesh:
  Face 0: 3 (1.000000, 0.000000, 1.000000), 1 (0.848485, 0.000000,
0.015152), 2 (-0.818182, 0.000000, -0.818182), 0 (0.015152, 0.000000,
0.848485)

Is this what I'm supposed to be seeing?

Thanks,

-- Ryan Viertel

**Comment by ghost** [comment]
I've successfully been able to extract several quad meshes using the command line tool, so I think its safe to close the issue.

Thanks again
