### ISSUE TITLE
Preserving boundary while extracting quad-mesh

### ISSUE THREAD

**Issue by VVingerfly** [hcebke/libQEx#6]
Hello! Are there any methods to preserve the boundary of original triangle mesh while extracting quad-mesh. Preserving boundary means keeping all the boundary vertices of resulting quad-mesh lying on the boundary edges of triangle mesh.

Here is the result of libQEx.
![image](https://cloud.githubusercontent.com/assets/16233971/21836441/2c3c8948-d800-11e6-9a2f-728227a41cb9.png)

Can libQEx keep boundary while extracting quad-mesh from open triangle mesh?

**Comment by hcebke** [comment]
The short answer is: no. If you had a parametrization with integer iso-lines aligned with the boundary, then libQEx would naturally extract the boundary of the triangle mesh.

On the mesh depicted in your image I'm not even sure what kind of behavior you desire. Do you want the iso-lines of your parametrization to be traced to the boundaries and then connected via the boundary? That would result in non-quadrilateral faces. That's nothing libQEx supports but you could extend it to do exactly this. It would incur considerable effort, though.

**Comment by VVingerfly** [comment]
Thank you for your reply!
Yes, I want the iso-lines of parameterization to be traced to the boundary, so the boundary vertices of final quad-mesh lie on the boundary of triangle mesh.
Maybe the parameterization method should be modified or changed first. Currently I am using MIQ method.

Best,
Wei

**Comment by hcebke** [comment]
If you want your final mesh to be quad-only, i.e. if you do not want any non-quadrilateral faces, then you have to synthesize a different parametrization. The MIQ algorithm generally supports boundary alignment. You would have to treat the boundary edges of the input mesh as feature edges, i.e. constrain them to integer coordinates and add cross field alignment constraints to their incident faces.

None of that has anything to do with libQEx, though. If you feed it a boundary-aligned parametrization then it will extract a boundary-aligned quad mesh.

**Comment by VVingerfly** [comment]
Thanks a lot for your kind reply. They are very useful for me. I will look into MIQ algorithm in deeper, and treat the boundary edges as feature edges as you suggested. Thanks a lot.

Best,
Wei
